import 'bootstrap/dist/css/bootstrap.css'

import { Globalprovider } from "@/GlobalProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Globalprovider>{children}</Globalprovider>

        <Script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js'></Script>
        <Script src='https://kit.fontawesome.com/b6b7b8a602.js'></Script>
      </body>
    </html>
  );
}
